### ISSUE TITLE
about the opt_params

### ISSUE THREAD

**Issue by chZzZzZz** [RomuloDrumond/LSSVM#1]
Hi,your code is very nice! I have a question that when you compute alpha and b in opt_params,your formula is different from the formula I searched in wiki:
![图片](https://user-images.githubusercontent.com/32059088/61864440-04657a00-af04-11e9-914b-8b0e8c66881d.png)

I read your code and I think your formula is :
![图片](https://user-images.githubusercontent.com/32059088/61865843-8e164700-af06-11e9-9fcb-1bd258aa931f.png)

how did you get your formula?

**Comment by RomuloDrumond** [comment]
You can find it in equation 20 of the paper: https://link.springer.com/content/pdf/10.1023%2FA%3A1018628609742.pdf
