### ISSUE TITLE
some bugs in rbf kernel

### ISSUE THREAD

**Issue by DannyVanpoucke** [RomuloDrumond/LSSVM#6]
Dear Romulo Drumond,

First of, very nice work on the implementation of the LS-SVM. I'm currently building my own LS-SVM regressor and drawing inspiration from your code ;-). While looking at the rbf kernel, I couldn't help but notice a few bugs:
 - [ ] : **`if x_i.ndim==x_i.ndim and x_i.ndim==2: # both matrice`** <br/>I guess the second x_i should have been x_j
 - [ ] : **```else: # both vectors or a vector and a matrix
                return exp( -( dot(x_i,x_i.T) + dot(x_j,x_j.T)- 2*dot(x_i,x_j) ) / sigma**2 )```**
This is only correct for vectors. Once either x_j or x_i is a matrix, the dot function will give you the wrong result. *e.g.* in case of a vector and matrix, the result should be a vector, but you will get a matrix, as the dot of a matrix with itself will give you a matrix. ;-) I'm afraid you'll have to create your own dot-functionality for that. Note that where pen and paper math of vect*vect^T = scalar, and vect^T*vect=matrix, numpy arithmetic gives a scalar for both. 

Best,
Danny

**Comment by RomuloDrumond** [comment]
Ops, sorry for the delay but I think I fixed these issues on the last commit.

**Comment by DannyVanpoucke** [comment]
No problem. Your code was an interesting learning exercise for my own implementation of LSSVM (needed the scikit API).
